name: build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        device: [g34]
    name: "🚧 Build for ${{matrix.device}}"

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0          # Required to access specific commit
          submodules: false       # We'll manually sync submodules

      - name: Checkout specific commit and update submodules
        run: |
          git checkout 3a75ba3edb322a668b02f0d050554cfd7f240f30
          git submodule update --init --recursive

      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Kolkata"

      - name: Setup Toolchains
        run: |
          sudo apt update
          sudo apt install bison flex libssl-dev libarchive-tools -y
          mkdir -p toolchain
          cd toolchain
          echo 'Download antman and sync'
          bash <(curl -s "https://raw.githubusercontent.com/Neutron-Toolchains/antman/main/antman") -S=05012024
          echo 'Done'

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 30

      - name: Run build
        run: |
          DEVICE=${{matrix.device}} KSU=1 ./build.sh

      - name: Upload kernel
        uses: actions/upload-artifact@v4
        with:
          name: O_kernel-${{matrix.device}}
          path: AnyKernel3/O*.zip

      - name: Upload to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          document: AnyKernel3/O*.zip
          message: "✅ Build for `${{matrix.device}}` completed successfully!"
